version: '3'

services:
  nginx:
    image: nginx
    volumes:
     - ./:/var/www/
     - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/lardocker/Dockerfile
    volumes:
      - ./:/var/www
    container_name: app








